### PR TITLE
Update maintainers.yml

### PR DESCRIPTION
**Pull request by eLopez6**
Testing to see if we can update the website

### CODE REVIEW

**Comment by eLopez6** [comment]
To be clear... the information I'm updating is correct and up to date.

**Review by thomasrussellmurphy — APPROVED** [review]
Changes look good.

**Comment by timtadh** [comment]
:+1: LGTM

**Comment by timtadh** [comment]
Do you want me to hit the merge button? Do you have all  the access you need?

**Comment by eLopez6** [comment]
I do not have any access. That was part of this test haha

**Comment by timtadh** [comment]
I just added you as an owner of the hacsoc organization. Goto https://github.com/hacsoc to confirm or click the link your email.

**Pull request merged**
