### PR TITLE
migrate to jekyll

### PR DESCRIPTION
**Pull request by ajm188**
I recommend stepping through commit-by-commit. I tried my best to keep them small, but some - especially those that involved `rm`ing files - were necessarily large.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Looks like a solid set of changes! Thanks for the effort. I'm not sure how well this stands, technically, but it looks good in my scan of the changes.

**Comment by ajm188** [comment]
One important thing that I should have noted originally:

This PR moves us over to jekyll without changing the UI, _except_ for the contact page. I changed this because I could not come up with a way to programmatically join a list of names in a grammatically correct way (i.e. One, Two, Three vs One, Two, and Three). So, three options, in increasing order of estimated effort:
1. decide we're happy with the way it looks now
2. revert the change that moves the maintainer/officer info to yaml files
3. figure out to do the thing I talked about above in liquid/jekyll

**Comment by ajm188** [comment]
Here is a screenshot of what it looks like now:
screen shot 2016-04-07 at 11 15 41 am

**Comment by timtadh** [comment]
@ajm188 First comment, `README.md` should contain directions for compiling and viewing the site locally. Don't assume anyone knows how anything works because you will eventually have a newbie who wants to edit the site.

Probably want to link to : https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/ plus docs on how to get ruby setup with rbenv.

**Comment by timtadh** [comment]
Looks like events page isn't centering the calendar:

hacsoc-events

**Comment by timtadh** [comment]
@ajm188 modulus my comments above looks great! ready to :+1: if you put some stuff in the README about jekyll. Also I have a hard time typing jekyll.

**Comment by ajm188** [comment]
Thanks for the feedback. I will update the README. For the record, the events calendar is already like that. I am bad at css, but trying to figure out how to fix it.

**Comment by ajm188** [comment]
I fixed it! Have to run to class, but will push commits later. Still have to add content to README.

**Comment by ajm188** [comment]
@timtadh updated

**Comment by ajm188** [comment]
Are we good to merge this?

**Comment by timtadh** [comment]
Yes. :+1:

**Pull request merged**
